//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PilgrimageCommunication.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PilgrimageCommunication.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string RegistrationTitleTxt {
            get {
                return ResourceManager.GetString("RegistrationTitleTxt", resourceCulture);
            }
        }
        
        internal static string WelcomeTxt {
            get {
                return ResourceManager.GetString("WelcomeTxt", resourceCulture);
            }
        }
        
        internal static string LanguageSelectText {
            get {
                return ResourceManager.GetString("LanguageSelectText", resourceCulture);
            }
        }
        
        internal static string CountryCodePickerText {
            get {
                return ResourceManager.GetString("CountryCodePickerText", resourceCulture);
            }
        }
        
        internal static string SendVerificationNumberBtnText {
            get {
                return ResourceManager.GetString("SendVerificationNumberBtnText", resourceCulture);
            }
        }
        
        internal static string VerificationTitleTxt {
            get {
                return ResourceManager.GetString("VerificationTitleTxt", resourceCulture);
            }
        }
        
        internal static string EnterVerCodeTxt {
            get {
                return ResourceManager.GetString("EnterVerCodeTxt", resourceCulture);
            }
        }
        
        internal static string ConfirmVerificationNumberBtnText {
            get {
                return ResourceManager.GetString("ConfirmVerificationNumberBtnText", resourceCulture);
            }
        }
        
        internal static string DashboardTitleTxt {
            get {
                return ResourceManager.GetString("DashboardTitleTxt", resourceCulture);
            }
        }
        
        internal static string YourLocTxt {
            get {
                return ResourceManager.GetString("YourLocTxt", resourceCulture);
            }
        }
        
        internal static string LimitationTxt {
            get {
                return ResourceManager.GetString("LimitationTxt", resourceCulture);
            }
        }
    }
}
